DistCompiler/pgo

- examples/counter.tla
- examples/round_robin.tla
- src/pgo/parser/TLAParser.java
- src/pgo/trans/intermediate/TLABuiltins.java
This PR fixes the conflict between the binary and unary `-` operators by automatically renaming the unary `-` operator to `-_` during parsing. (as per convention when describing the arity of an operator in TLA+).
It turns out that this is the only operator in all of TLA+ that has this issue. All other operators have distinct names no matter their arity.
Experimenting with TLC has confirmed that any operators sharing a name is invalid. The irony here is that if you redefine `_-_` and `-_` manually, it is actually also forbidden. Only the special-case definition in `Integers` and `Reals` is allowed.
> All names should have only one meaning
-Lamport
Fixes #70
> Fix conflict between unary and binary `-` operator

- src/pgo/trans/intermediate/BuiltinModule.java
- src/pgo/trans/intermediate/TLABuiltins.java
Based on: https://lamport.azurewebsites.net/tla/summary.pdf
> Support operator symbols that have the same semantics.

- src/pgo/parser/ParseAction.java
- src/pgo/parser/ParseTools.java
- src/pgo/parser/TLAParser.java
This is my attempt at clarifying how the TLA+ parser works - let me know if it makes sense.
There are no intended feature changes. Addresses #54 .
> Added javadoc to "common vocabulary" TLA+ parser methods

- src/pgo/trans/intermediate/TLAExpressionCodeGenVisitor.java
- src/pgo/trans/passes/type/TLAExpressionTypeConstraintVisitor.java
- test/pgo/ExpressionCodeGenRunFailureTest.java
- test/pgo/ExpressionCodeGenRunTest.java
- test/pgo/IntegrationTestingUtils.java
I implemented the case expression using a series of if statements and gotos (thanks to Finn for the goto idea), which I think is the most readable of the various ways it could have been implemented. The other was handled by setting the default value of the result variable when the other arm is present, and adding a panic if no cases match otherwise.
I implemented failure testing for expected panics, but the logic is still rather rudimentary. Let me know if you want me to fix it up.
> Add support for case expressions. Add failure tests.

- src/pgo/parser/PlusCalParser.java
- test/integration/ProceduresPSyntax.tla
- test/integration/SingleProcess.tla
- test/pgo/TestCodeGenRunTest.java
This updates the grammar for P-syntax PlusCal specs, which had the same issue of not recognizing procedures and macros taking no parameters.
I also added an integration test for single-process specs.
> Procedures in P-syntax

- .travis.yml
Found no issues on my machine. This updates our Travis configuration to run the test suite on both versions, since it wouldn't hurt to remain compatible.
> Run test suite on Java versions 8 and 9.

- src/pgo/PGoNetOptions.java
- src/pgo/PGoOptions.java
- test/pgo/PGoNetOptionsTest.java
Small fixes while I was reading the updated manual:
* remove unused code related to the now removed `writeAST` option;
* use `state-server` as the default distributed state strategy
* we were getting an exception if we invoked the `./pgo.sh` script without any arguments. We now print the help message.
> Cosmetic changes

- examples/mpcal/dqueue.tla
- src/pgo/PGoMain.java
- src/pgo/PGoOptions.java
- src/pgo/trans/intermediate/ModularPlusCalLabelingRulesVisitor.java
- test/pgo/IntegrationTestingUtils.java
- test/pgo/trans/intermediate/ModularPlusCalLabelingRulesTest.java
Now if you invoke PGo with `-m`, it will attempt to compile an MPCal spec to PlusCal (instead of the traditional spec -> Go compilation pipeline).
I also added an example MPCal spec (a version of `dqueue` in Modular PlusCal) and integrated the validation pass introduced in #94.
> Add compilation flag to indicate MPCal -> PCal compilation

- examples/mpcal/dqueue.tla
- src/pgo/PGoMain.java
- src/pgo/model/mpcal/ModularPlusCalBuilder.java
- src/pgo/model/mpcal/ModularPlusCalInstance.java
- src/pgo/model/mpcal/ModularPlusCalNodeFormattingVisitor.java
- src/pgo/model/tla/TLAOperatorCall.java
- src/pgo/parser/ModularPlusCalParser.java
- src/pgo/parser/PlusCalParser.java
- src/pgo/parser/ReferenceGrammar.java
- src/pgo/parser/TLAParser.java
- test/pgo/parser/ModularPlusCalParserTest.java
- test/pgo/parser/ModularPlusCalUnitParserTest.java
- test/pgo/parser/PlusCalUnitParserTest.java
This removes Modular PlusCal bits from the PlusCal grammar. Unfortunately, composing pieces of the grammar in an "intuitive" way is not easy. The approach taken in this pull request is to transform every piece of grammar that needs to be changed to a `ReferencedGrammar`. Then, `ModularPlusCalParser` overwrites the underlying grammar definition with the changes specific to the additions to the language we introduced.
See the `overwriteGrammars` method for more information.
The result of these changes is that using `yield`, special variables (`$variable`) or `ref` in PlusCal specs results in a parse error, as it should.
> Do not allow Modular PlusCal syntax in PlusCal specs

- src/pgo/trans/intermediate/TLABuiltins.java
I'd like to use some operators/modules for which we currently do not have code generation/type system support. One example of which is the `FiniteSets` module and the `Cardinality` operator.
I think it's reasonable to expect that PGo should be able to compile MPCal => PlusCal in specs that make use of these features, but fail to generate a Go implementation if requested because that is currently unsupported.
This is what this pull request is changing. Let me know if you have thoughts.
(This is related to #106)
> Proposal: unsupported operators

- src/pgo/parser/ModularPlusCalParser.java
- src/pgo/parser/TLAParser.java
- test/pgo/formatters/TLANodePrintEquivalenceTest.java
I tried a few things to make the TLA+ parser faster, but the more I try the more it occurs to me that the design itself is slow. There's no obvious exponential backtracking when I trace parser execution, so nothing that can be fixed without a much more sophisticated tweak to parser control flow (which would affect the most complex and bug-prone part of the parser: the expression parser).
As such, for the sake of getting results now I disabled parsing the translated TLA+ code. This nets a significant speedup, since most of the TLA+ PGo had to parse was in there. This broke one test which relied on capturing units during / after the translation, which I commented out with a note as to why.
I hope to return one day with a proper fix for this, which may be an actually fast parser based on my …
> Improved TLA+ parse phase speed via hack

- .github/workflows/ci.yml
- README.md
Our CI is broken right now, and Travis has been phasing out. This commit enables the new shiny, and should work with the new sbt setup.
> Enable Github CI

- .github/workflows/ci.yml
- README.md
- build.sbt
- distsys/go.mod
- distsys/tlaplus.go
- distsys/tlaplus_test.go
- test/files/general/ExprTests.tla.gotests/go.mod
- test/files/general/dqueue.tla.gotests/go.mod
- test/files/general/load_balancer.tla.gotests/go.mod
- test/files/general/replicated_kv.tla.gotests/go.mod
- test/pgo/DistsysTests.scala
- test/pgo/TLAExpressionFuzzTests.scala
As a first step in addressing issue #138 , it's fairly simple to bring the README up to date.
Many small details about how to build, run, etc are changed. Very out-of-date info is purged, and notes are made that the manual still needs updating (work in progress...).
While doing so, I realised the old README referred to a version matrix CI used to use, so I re-implemented that in the Github CI action with what I believe are currently reasonable versions. Now, that part of the README will be correct again.
> Bring README up to date, bring CI back to old glory

- src/pgo/PGo.scala
It's quite annoying to have to manually go fmt PGo's not-quite-go-fmt-compatible output.
This PR adds a quick attempt to fmt the output after gogen, printing a little warning if it fails for some reason.
> Add automatic go fmt call on gogen

- src/pgo/trans/MPCalSemanticCheckPass.scala
- src/pgo/util/MPCalPassUtils.scala
- test/files/general/proxy_w_macro.tla
- test/files/general/proxy_w_macro.tla.expectpcal
- test/files/general/proxy_w_macro.tla.gotests/go.mod
- test/files/general/proxy_w_macro.tla.gotests/go.sum
- test/files/general/proxy_w_macro.tla.gotests/proxy_w_macro.go
- test/files/general/proxy_w_macro.tla.gotests/proxy_w_macro_test.go
The test/files/general/proxy_w_macro.tla test case exposes an unintentionally restrictive check in PGo's front-end.
Especially given how we go out of our way to handle unbound names in macro definitions, it's unreasonable to forbid unbound labels.
The fix is quite easy: make sure we only check label coherence at expansion site. The check still does all the useful things, and does not reject @shayanh 's existing specs :)
> Test and fix unbound label error in unexpanded macro

- src/pgo/PGo.scala
- src/pgo/parser/TLAParser.scala
- src/pgo/util/TLAExprInterpreter.scala
- test/files/general/ExprTests.tla.expectpcal
- test/files/general/dqueue.tla.expectpcal
- test/files/general/load_balancer.tla.expectpcal
- test/files/general/proxy.tla.expectpcal
- test/files/general/proxy_w_macro.tla.expectpcal
- test/files/general/proxy_w_macro.tla.gotests/proxy_w_macro.go
- test/files/general/replicated_kv.tla.expectpcal
- test/files/pcalgen/BadPCalMarkerPlacementBeginMissing.tla
- test/files/pcalgen/BadPCalMarkerPlacementBothMissing.tla
- test/files/pcalgen/BadPCalMarkerPlacementEndMissing.tla
- test/files/pcalgen/BadPCalMarkerPlacementSwapped.tla
- test/pgo/FileTestSuite.scala
- test/pgo/util/TLAExprInterpreterTests.scala
- Replace janky regex trickery with a tiny parser system, so we can report pretty positional errors if people mess up tag placement
- Add tests for most cases of this now-real error
- Notice that multiple test cases were previously hiding wrong behaviour (PGo just not writing its PCal output sometimes, without telling anyone... eep!), and this this change fixed them
- Additionally, this change removes a little bit of newline padding that would, if PGo were run repeatedly in the same file in pcalgen mode (an expected situation), slowly add more and more newlines to the TLA+ file.
> Make PlusCal marker issues a real error, not an assertion

- src/pgo/trans/MPCalNormalizePass.scala
- test/files/pcalgen/DontEatMyLabels.tla
- test/files/pcalgen/DontEatMyLabels.tla.expectpcal
Fixes #188.
It turns out a tiny edge case was missing in one of PGo's code transformation passes, which would end up deleting labeled code _only if it was inside an `else if`_ (a pattern which apparently did not appear until the issue-causing example).
This PR makes the tiny-but-ever-so-important change, and adds the file from the issue as a test case.
> Curb PGo's newly-discovered code deletion feature

- distsys/resources/gcounter.go
- test/files/general/gcounter.tla.gotests/gcounter_test.go
This commit fixes linter errors:
- %w directive doesn't work with log.Printf, log.Panicf.
- Comment formatting.
- Imports ordering.
> Very small improvements in gcounter resource and test.

- distsys/mpcalctx.go
- distsys/resources/fd.go
- distsys/resources/tcpmailboxes.go
This PR fixes the following [staticcheck](https://staticcheck.io/) errors:
```
/Users/shayan/src/github.com/UBC-NSS/pgo/distsys/mpcalctx.go
(26, 15)   ST1005  error strings should not be capitalized
(411, 19)  S1040   type assertion to the same type: res already has type ArchetypeResource
/Users/shayan/src/github.com/UBC-NSS/pgo/distsys/resources/fd.go
(284, 4)  SA4011  ineffective break statement. Did you mean to break out of the outer loop?
/Users/shayan/src/github.com/UBC-NSS/pgo/distsys/resources/tcpmailboxes.go
(204, 4)  SA4006  this value of doContinue is never used
(225, 4)  SA4006  this value of doContinue is never used
```
> fix staticcheck errors

- distsys/resources/gcounter.go
* Don't abort when given non-numerical values in WriteValue, no point in abort and retrying
* If the resource is currently in critical section from `ReadValue()` or `WriteValue()`, its local value cannot change, queue up the updates to be merged after exiting critical section. Currently queue gets cleared at `Abort()` and `Commit()`.
> GCounter resource fixes

- src/pgo/trans/MPCalGoCodegenPass.scala
- test/files/general/ExprTests.tla
- test/files/general/ExprTests.tla.expectpcal
- test/files/general/ExprTests.tla.gotests/ExprTests.go
- test/files/general/NestedCRDTImpl.tla.gotests/NestedCRDTImpl.go
- test/files/general/proxy.tla.gotests/proxy.go
- test/files/general/replicated_kv.tla.gotests/replicated_kv.go
- test/files/gogen/bug_167.tla.gotests/bug_167.go
Fixes #197, which helped me find two different bugs in the same ~20 LOC.
First, the reported bug: a scoping oversight meant that, unlike the rest of PGo, the handling of with statements during gogen did not consider the following to be valid:
```
with(x = 42, y = x) {
skip;
}
```
The result was a crash, because `x` should actually be in scope of `y`'s definition, and the rest of the gogen code assumed this.
The second bug is also caused by this same example: the usual mitigation for the Go compiler considering unused local variables an error was absent from code generation for `with` statements, meaning that the code generated from the example above would not compile (complaining `y` was unused).
To fix, you just add `_ = x` and `_ = y` to keep the Go compiler happy.
> Two for one deal on with statement gogen bugs

- src/pgo/model/pcal/AST.scala
- src/pgo/trans/MPCalPCalCodegenPass.scala
- src/pgo/trans/PCalRenderPass.scala
- test/files/general/NestedCRDTImpl.tla.expectpcal
- test/files/general/PBFail4_bug125.tla.expectpcal
- test/files/general/ProcedureSpaghetti.tla.expectpcal
- test/files/general/bug2_124.tla.expectpcal
- test/files/general/dqueue.tla.expectpcal
- test/files/general/load_balancer.tla.expectpcal
- test/files/general/pbkvs.tla.expectpcal
- test/files/general/proxy.tla.expectpcal
- test/files/general/replicated_kv.tla.expectpcal
- test/files/pcalgen/AssignmentRulesNoMultipleWrites.tla.expectpcal
- test/files/pcalgen/DontEatMyLabels.tla.expectpcal
- test/files/pcalgen/MappingMacroNestedWithExpansion.tla.expectpcal
- test/files/pcalgen/MultiWithSemantics.tla
- test/files/pcalgen/MultiWithSemantics.tla.expectpcal
- test/files/pcalgen/ResourceAccessBoundByWith.tla.expectpcal
- test/files/pcalgen/bug_195.tla.expectpcal
- test/files/pcalgen/bug_195_simple.tla.expectpcal
There was a potential bug in how with statements were being transformed PCal-side.
The issue involves multiple resource reads (with indices, if you really want broken output) across multiple declarations in a single with statement.
PCal codegen would lift all the resource reads above the with statement, potentially leading to incorrect scoping if one binding referenced another.
This change forcibly splits up all with statements into single bindings, ensuring this problem can't happen.
This change, however, made the output PCal even uglier, and, inspired by @shayanh's formatting of the in-progress Raft spec, I decided to also add a with statement de-nesting pass to PCal generation, alongside a prettier multi-declaration printing mode for with statements declaring more than one thing. As a …
> Improve with statement handling in generated PCal

- distsys/tla/symbols.go
- src/pgo/trans/MPCalGoCodegenPass.scala
- src/pgo/util/TLAExprInterpreter.scala
- test/files/general/ExprTests.tla
- test/files/general/ExprTests.tla.expectpcal
- test/files/general/ExprTests.tla.gotests/ExprTests.go
- test/files/general/ExprTests.tla.gotests/ExprTests_test.go
- test/files/general/PBFail4_bug125.tla.gotests/PBFail4_bug125.go
- test/files/general/pbkvs.tla.gotests/pbkvs.go
- test/files/general/proxy.tla.gotests/proxy.go
- test/files/general/replicated_kv.tla.gotests/replicated_kv.go
- test/files/gogen/bug_167.tla.gotests/bug_167.go
- test/pgo/util/TLAExprInterpreterTests.scala
Does what the title says.
It turns out (thanks, @shayanh!) that up until this point I had not considered that TLA+ boolean ops are short-circuiting.
Now, theoretically, (mumble mumble TLA+ book), but in practice they are treated that way.
So, these changes make sure PGo supports this. It makes boolean ops "special", and handles them in a short-circuiting way, unlike all other ops, which have all of their arguments pre-evaluated before being allowed to execute.
> Make TLA+ boolean operations short-circuit

- distsys/resources/channels.go
This fixes a bug where consecutive calls to `PreCommit()` and `Abort()` can put more items in `backlogBuffer` than really should be there.
> Fix an issue with channels

- distsys/resources/crdt.go
- test/files/general/aworset.tla.gotests/aworset_test.go
- test/files/general/gcounter.tla.gotests/gcounter_test.go
CRDT changes after couple of benchmark tests
* make broadcastInterval configurable
* change merge queue into a single merge value (the queued values can be merged themselves into a single value)
* close the RPC listener on Close()
* In `Receive`, do a preflight check to see if incoming state will result to new state with faster RLocking on stateMu. If the incoming merge isn't needed, discard.
StateLogger
* Log to specified file, the current CRDT value after performing 1. Write 2. Merge
* Turned on/off with `logStateEnabled` flag (maybe make sense to make it an env var instead...)
Selective broadcast
* Based on configurable `broadcastSize`, the `broadcast()` process will randomly select specified number of peers to try connecting and broadcast states only to these peers.
> CRDT changes for benchmark

- distsys/tla/symbols.go
- src/pgo/model/tla/BuiltinModules.scala
- src/pgo/util/TLAExprInterpreter.scala
- test/files/general/ExprTests.tla
- test/files/general/ExprTests.tla.expectpcal
- test/files/general/ExprTests.tla.gotests/ExprTests.go
- test/files/general/ExprTests.tla.gotests/ExprTests_test.go
Fixes #229.
The operator is quite simple, so there's not much to say. Some unit tests are included, as well as support for generating the operator during expression fuzzing.
> Add ToString operator to module TLC

- src/pgo/parser/TLAParser.scala
- src/pgo/trans/TLARenderPass.scala
- test/files/tla/Numbers.tla
- test/pgo/TLAUnitCoverageTests.scala
Numbers prefixed with `\h`, `\b`, and `\o` caused a parser error because the `\` character was not stripped before passing the string to a number constructor.
This PR will fix the issue mentioned above.
Note that the decimal syntax throws a separate error:
```
go.parser.DefinitionLookupError: 
identifier . does not refer to a known definition at /workspaces/pgo/test/files/tla/Numbers.tla:9.13-14
Decimal == 1.1
```
I have left this as a TODO in the added TLA+ file.
> fix parsing numbers with radix other than 10
